In [ ]:
name = "Nimra Mughal"
age = 45
m = 75
print("Name: ", name, "Age: ", age, "Marks: ",  m)
print("Name: ", name, "Age: ", age, "Marks: ",  m)
print("Name: ", name, "Age: ", age, "Marks: ",  m)
print("Name: ", name, "Age: ", age, "Marks: ",  m)

Name:  Nimra Mughal Age:  45 Marks:  75
Name:  Nimra Mughal Age:  45 Marks:  75
Name:  Nimra Mughal Age:  45 Marks:  75
Name:  Nimra Mughal Age:  45 Marks:  75